// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/Child.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    JImage: typeof import('./src/components/J-image.vue')['default']
    JNav: typeof import('./src/components/J-Nav.vue')['default']
    JNoticeBar: typeof import('./src/components/J-NoticeBar.vue')['default']
    JSwiper: typeof import('./src/components/J-Swiper.vue')['default']
    JTimeCount: typeof import('./src/components/J-TimeCount.vue')['default']
    JVideo: typeof import('./src/components/J-Video.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Phone: typeof import('./src/components/Phone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
  }
}

export {}
